// <auto-generated />
namespace WasteFoodDistributionSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class name_image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name_image));
        
        string IMigrationMetadata.Id
        {
            get { return "202303171349199_name_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
