// <auto-generated />
namespace WasteFoodDistributionSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class amount_clmn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(amount_clmn));
        
        string IMigrationMetadata.Id
        {
            get { return "202303171439014_amount_clmn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
